// apps/api/src/services/aiQueryExecutor.ts

import { QueryPlan, QueryStep, QueryResult, RouteInfo, generateSummary } from "./ollamaService.js";
import { arcgisPostJson } from "./arcgisRest.js";
import { GEOMETRY_SERVER } from "./overlays/overlayRegistry.js";

// Geocoder URL from environment
const GEOCODER_URL = process.env.HC_COMPOSITE_URL?.replace(/\/+$/, "") ||
  "https://maps.hillsboroughcounty.org/arcgis/rest/services/Geocoding/Composite_Address_Locator_Overall/GeocodeServer";

// ArcGIS Online Routing Service
const ROUTING_URL = "https://route-api.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World/solve";
const ARCGIS_API_KEY = process.env.ARCGIS_API_KEY || "";

interface Feature {
  attributes: Record<string, any>;
  geometry?: {
    rings?: number[][][];
    paths?: number[][][];
    x?: number;
    y?: number;
    spatialReference?: { wkid: number };
  };
}

interface QueryResponse {
  features: Feature[];
  error?: { message: string };
}

// Execute a query plan generated by the LLM
export async function executeQueryPlan(
  question: string,
  plan: QueryPlan
): Promise<QueryResult> {
  const stepResults: Map<number, Feature[]> = new Map();

  try {
    for (const step of plan.steps) {
      console.log(`Executing step ${step.stepNumber}: ${step.description}`);

      const features = await executeStep(step, stepResults);
      stepResults.set(step.stepNumber, features);

      console.log(`Step ${step.stepNumber} returned ${features.length} features`);
    }

    // Get final results from last step
    const lastStepNumber = Math.max(...plan.steps.map(s => s.stepNumber));
    const finalResults = stepResults.get(lastStepNumber) || [];

    // Include both attributes and geometry for map visualization
    // If outputFields is specified, order results with those fields first
    const results = finalResults.map(f => {
      const attrs = f.attributes;

      // If outputFields specified, build ordered result with those fields first
      if (plan.outputFields && plan.outputFields.length > 0) {
        const ordered: Record<string, any> = {};

        // Add outputFields first (in order)
        for (const field of plan.outputFields) {
          // Check for case-insensitive match
          const matchingKey = Object.keys(attrs).find(
            k => k.toLowerCase() === field.toLowerCase()
          );
          if (matchingKey) {
            ordered[matchingKey] = attrs[matchingKey];
          }
        }

        // Add geometry if present
        if (f.geometry) {
          ordered._geometry = f.geometry;
        }

        return ordered;
      }

      // Default: include all attributes
      return {
        ...attrs,
        ...(f.geometry && { _geometry: f.geometry })
      };
    });

    // Find geocoded location if there was a geocode step (to show origin point on map)
    let geocodedLocation: { address: string; geometry: any } | undefined;
    for (const step of plan.steps) {
      if (step.action === "geocode") {
        const geocodeResult = stepResults.get(step.stepNumber);
        if (geocodeResult && geocodeResult.length > 0) {
          geocodedLocation = {
            address: geocodeResult[0].attributes.ADDRESS || step.address || "",
            geometry: geocodeResult[0].geometry
          };
        }
        break;
      }
    }

    // Calculate route if this was a nearest query and we have both origin and destination
    let route: RouteInfo | undefined;
    const hasNearestStep = plan.steps.some(s => s.action === "nearest");
    const hasRouteStep = plan.steps.some(s => s.action === "route");

    // Check if route was calculated by route action
    if (hasRouteStep && finalResults.length > 0) {
      const routeResult = finalResults[0];
      if (routeResult.attributes?._routeInfo) {
        route = routeResult.attributes._routeInfo;
        // Also set geocodedLocation from origin
        if (routeResult.attributes._originGeometry) {
          geocodedLocation = {
            address: routeResult.attributes.ORIGIN || "",
            geometry: routeResult.attributes._originGeometry
          };
        }
        console.log(`Route from route action: ${route?.totalDistance?.toFixed(2) ?? 'unknown'} miles, ${route?.totalTime?.toFixed(0) ?? 'unknown'} minutes`);
      }
    }
    // Calculate route for nearest queries
    else if (hasNearestStep && geocodedLocation?.geometry && finalResults.length > 0) {
      const fromPoint = { x: geocodedLocation.geometry.x, y: geocodedLocation.geometry.y };

      // Get destination point from the first result
      const destGeom = finalResults[0]?.geometry;
      let toPoint: { x: number; y: number } | null = null;

      if (destGeom?.x !== undefined && destGeom?.y !== undefined) {
        // Point geometry
        toPoint = { x: destGeom.x, y: destGeom.y };
      } else if (destGeom?.rings) {
        // Polygon - use centroid
        const centroid = calculateCentroid(destGeom.rings);
        toPoint = centroid;
      }

      if (toPoint) {
        console.log("Calculating route from", fromPoint, "to", toPoint);
        const routeResult = await getRoute(fromPoint, toPoint);
        if (routeResult) {
          route = routeResult;
          console.log(`Route calculated: ${route.totalDistance.toFixed(2)} miles, ${route.totalTime.toFixed(0)} minutes`);
        }
      }
    }

    // Generate natural language summary
    const summary = await generateSummary(question, results);

    return {
      success: true,
      question,
      plan,
      results,
      summary,
      geocodedLocation,
      route
    };
  } catch (error) {
    console.error("Query execution error:", error);
    return {
      success: false,
      question,
      plan,
      results: [],
      summary: "",
      error: error instanceof Error ? error.message : "Unknown error"
    };
  }
}

async function executeStep(
  step: QueryStep,
  previousResults: Map<number, Feature[]>
): Promise<Feature[]> {
  switch (step.action) {
    case "geocode":
      return executeGeocode(step);

    case "query":
      return executeQuery(step);

    case "buffer":
      return executeBuffer(step, previousResults);

    case "intersect":
      return executeIntersect(step, previousResults);

    case "nearest":
      return executeNearest(step, previousResults);

    case "queryAtPoint":
      return executeQueryAtPoint(step, previousResults);

    case "filter":
      return executeFilter(step, previousResults);

    case "count":
      return executeCount(step, previousResults);

    case "route":
      return executeRoute(step);

    default:
      throw new Error(`Unknown action: ${step.action}`);
  }
}

async function executeQuery(step: QueryStep): Promise<Feature[]> {
  if (!step.layerUrl) {
    throw new Error(`No URL for layer: ${step.layerKey}`);
  }

  const queryUrl = `${step.layerUrl}/query`;
  const params: Record<string, any> = {
    where: step.whereClause || "1=1",
    outFields: "*",
    returnGeometry: true,
    f: "json",
    outSR: 102100
  };

  const result = await arcgisPostJson<QueryResponse>(queryUrl, params);

  if (result.error) {
    throw new Error(`Query failed: ${result.error.message}`);
  }

  return result.features || [];
}

async function executeBuffer(
  step: QueryStep,
  previousResults: Map<number, Feature[]>
): Promise<Feature[]> {
  // Get features from the previous step or query the layer
  let sourceFeatures: Feature[];

  if (step.stepNumber > 1) {
    sourceFeatures = previousResults.get(step.stepNumber - 1) || [];
  } else {
    sourceFeatures = await executeQuery(step);
  }

  if (sourceFeatures.length === 0) {
    return [];
  }

  // Convert buffer unit to ESRI unit code
  const unitCode = getUnitCode(step.bufferUnit || "feet");
  const distance = step.bufferDistance || 100;

  // Prepare geometries for buffer operation
  const geometries = sourceFeatures
    .filter(f => f.geometry)
    .map(f => f.geometry);

  if (geometries.length === 0) {
    return sourceFeatures;
  }

  // Determine geometry type
  const sampleGeom = geometries[0];
  let geometryType = "esriGeometryPolygon";
  if (sampleGeom?.x !== undefined) {
    geometryType = "esriGeometryPoint";
  } else if (sampleGeom?.paths) {
    geometryType = "esriGeometryPolyline";
  }

  // Call geometry service buffer
  const bufferUrl = `${GEOMETRY_SERVER}/buffer`;
  const bufferParams = {
    f: "json",
    geometries: JSON.stringify({
      geometryType,
      geometries
    }),
    inSR: 102100,
    outSR: 102100,
    distances: String(distance),
    unit: String(unitCode),
    unionResults: "true"
  };

  const bufferResult = await arcgisPostJson<{ geometries: any[] }>(bufferUrl, bufferParams);

  if (!bufferResult.geometries || bufferResult.geometries.length === 0) {
    throw new Error("Buffer operation returned no geometries");
  }

  // Return buffered geometries as features
  return bufferResult.geometries.map((geom, idx) => ({
    attributes: { BUFFER_ID: idx, SOURCE_COUNT: sourceFeatures.length },
    geometry: {
      rings: geom.rings,
      spatialReference: { wkid: 102100 }
    }
  }));
}

async function executeIntersect(
  step: QueryStep,
  previousResults: Map<number, Feature[]>
): Promise<Feature[]> {
  if (!step.layerUrl) {
    throw new Error(`No URL for layer: ${step.layerKey}`);
  }

  // Get the buffer geometry from previous step
  const previousStep = step.stepNumber - 1;
  const bufferFeatures = previousResults.get(previousStep) || [];

  if (bufferFeatures.length === 0) {
    return [];
  }

  // Use the first buffer geometry (union result)
  const bufferGeometry = bufferFeatures[0]?.geometry;

  if (!bufferGeometry?.rings) {
    throw new Error("No valid buffer geometry for intersection");
  }

  // Query the target layer using the buffer geometry
  const queryUrl = `${step.layerUrl}/query`;
  const params: Record<string, any> = {
    where: step.whereClause || "1=1",
    geometry: JSON.stringify({
      rings: bufferGeometry.rings,
      spatialReference: { wkid: 102100 }
    }),
    geometryType: "esriGeometryPolygon",
    spatialRel: "esriSpatialRelIntersects",
    inSR: 102100,
    outFields: "*",
    returnGeometry: true,
    f: "json",
    outSR: 102100
  };

  const result = await arcgisPostJson<QueryResponse>(queryUrl, params);

  if (result.error) {
    throw new Error(`Intersection query failed: ${result.error.message}`);
  }

  return result.features || [];
}

async function executeFilter(
  step: QueryStep,
  previousResults: Map<number, Feature[]>
): Promise<Feature[]> {
  const previousStep = step.stepNumber - 1;
  const features = previousResults.get(previousStep) || [];

  if (!step.whereClause) {
    return features;
  }

  // Simple attribute filter (for complex SQL, would need proper parser)
  // This handles basic cases like "FIELD = 'value'" or "FIELD > 100"
  return features.filter(f => {
    try {
      return evaluateWhereClause(f.attributes, step.whereClause!);
    } catch {
      return true; // Include if we can't evaluate
    }
  });
}

async function executeCount(
  step: QueryStep,
  previousResults: Map<number, Feature[]>
): Promise<Feature[]> {
  const previousStep = step.stepNumber - 1;
  const features = previousResults.get(previousStep) || [];

  return [{
    attributes: {
      COUNT: features.length,
      LAYER: step.layerKey
    }
  }];
}

function getUnitCode(unit: string): number {
  const units: Record<string, number> = {
    feet: 9003,      // US Survey Feet
    miles: 9035,     // US Miles
    meters: 9001,    // Meters
    kilometers: 9036 // Kilometers
  };
  return units[unit.toLowerCase()] || 9003;
}

function evaluateWhereClause(attributes: Record<string, any>, clause: string): boolean {
  // Very basic WHERE clause evaluation
  // Supports: field = 'value', field > number, field < number, field LIKE '%pattern%'

  const equalMatch = clause.match(/(\w+)\s*=\s*'([^']+)'/i);
  if (equalMatch) {
    const [, field, value] = equalMatch;
    return String(attributes[field]).toLowerCase() === value.toLowerCase();
  }

  const gtMatch = clause.match(/(\w+)\s*>\s*(\d+)/i);
  if (gtMatch) {
    const [, field, value] = gtMatch;
    return Number(attributes[field]) > Number(value);
  }

  const ltMatch = clause.match(/(\w+)\s*<\s*(\d+)/i);
  if (ltMatch) {
    const [, field, value] = ltMatch;
    return Number(attributes[field]) < Number(value);
  }

  const likeMatch = clause.match(/(\w+)\s+LIKE\s+'%([^%]+)%'/i);
  if (likeMatch) {
    const [, field, pattern] = likeMatch;
    return String(attributes[field]).toLowerCase().includes(pattern.toLowerCase());
  }

  return true; // Default to include if we can't parse
}

async function executeGeocode(step: QueryStep): Promise<Feature[]> {
  if (!step.address) {
    throw new Error("Geocode action requires an address");
  }

  const url = new URL(`${GEOCODER_URL}/findAddressCandidates`);
  url.searchParams.set("f", "json");
  url.searchParams.set("SingleLine", step.address);
  url.searchParams.set("outFields", "*");
  url.searchParams.set("maxLocations", "1");
  url.searchParams.set("outSR", "102100");

  const response = await fetch(url.toString());
  if (!response.ok) {
    throw new Error(`Geocode failed: ${response.status} ${response.statusText}`);
  }

  const json: any = await response.json();
  const candidates = json.candidates || [];

  if (candidates.length === 0) {
    throw new Error(`Could not geocode address: ${step.address}`);
  }

  const candidate = candidates[0];
  return [{
    attributes: {
      ADDRESS: candidate.address,
      SCORE: candidate.score,
      ...candidate.attributes
    },
    geometry: {
      x: candidate.location.x,
      y: candidate.location.y,
      spatialReference: { wkid: 102100 }
    }
  }];
}

async function executeNearest(
  step: QueryStep,
  previousResults: Map<number, Feature[]>
): Promise<Feature[]> {
  if (!step.layerUrl) {
    throw new Error(`No URL for layer: ${step.layerKey}`);
  }

  // Get the point from the previous step (usually a geocode result)
  const previousStep = step.stepNumber - 1;
  const previousFeatures = previousResults.get(previousStep) || [];

  if (previousFeatures.length === 0) {
    throw new Error("No location from previous step for nearest query");
  }

  const sourceGeom = previousFeatures[0]?.geometry;
  if (sourceGeom?.x === undefined || sourceGeom?.y === undefined) {
    throw new Error("Previous step did not return a valid point geometry");
  }

  const maxResults = step.maxResults || 1;

  // Query all features from the target layer
  const queryUrl = `${step.layerUrl}/query`;
  const params: Record<string, any> = {
    where: step.whereClause || "1=1",
    outFields: "*",
    returnGeometry: true,
    f: "json",
    outSR: 102100
  };

  const result = await arcgisPostJson<QueryResponse>(queryUrl, params);

  if (result.error) {
    throw new Error(`Query failed: ${result.error.message}`);
  }

  const features = result.features || [];

  if (features.length === 0) {
    return [];
  }

  // Source point coordinates (already validated above)
  const sourceX = sourceGeom.x!;
  const sourceY = sourceGeom.y!;

  // Calculate distance to each feature and sort
  const featuresWithDistance = features.map(f => {
    let distance = Infinity;

    if (f.geometry) {
      if (f.geometry.x !== undefined && f.geometry.y !== undefined) {
        // Point geometry - direct distance
        distance = Math.sqrt(
          Math.pow(f.geometry.x - sourceX, 2) +
          Math.pow(f.geometry.y - sourceY, 2)
        );
      } else if (f.geometry.rings) {
        // Polygon geometry - distance to centroid
        const centroid = calculateCentroid(f.geometry.rings);
        distance = Math.sqrt(
          Math.pow(centroid.x - sourceX, 2) +
          Math.pow(centroid.y - sourceY, 2)
        );
      }
    }

    return { feature: f, distance };
  });

  // Sort by distance and take top N
  featuresWithDistance.sort((a, b) => a.distance - b.distance);
  const nearest = featuresWithDistance.slice(0, maxResults);

  // Add distance to attributes (convert from meters to feet for readability)
  return nearest.map(({ feature, distance }) => ({
    ...feature,
    attributes: {
      ...feature.attributes,
      DISTANCE_FEET: Math.round(distance * 3.28084), // Web Mercator units are roughly meters
      DISTANCE_MILES: Math.round(distance * 0.000621371 * 100) / 100
    }
  }));
}

async function executeQueryAtPoint(
  step: QueryStep,
  previousResults: Map<number, Feature[]>
): Promise<Feature[]> {
  if (!step.layerUrl) {
    throw new Error(`No URL for layer: ${step.layerKey}`);
  }

  // Get the point from the previous step (usually a geocode result)
  const previousStep = step.stepNumber - 1;
  const previousFeatures = previousResults.get(previousStep) || [];

  if (previousFeatures.length === 0) {
    throw new Error("No location from previous step for query at point");
  }

  const sourceGeom = previousFeatures[0]?.geometry;
  if (sourceGeom?.x === undefined || sourceGeom?.y === undefined) {
    throw new Error("Previous step did not return a valid point geometry");
  }

  // Query the layer using the point geometry
  const queryUrl = `${step.layerUrl}/query`;
  const params: Record<string, any> = {
    where: step.whereClause || "1=1",
    geometry: JSON.stringify({
      x: sourceGeom.x,
      y: sourceGeom.y,
      spatialReference: { wkid: 102100 }
    }),
    geometryType: "esriGeometryPoint",
    spatialRel: "esriSpatialRelIntersects",
    inSR: 102100,
    outFields: "*",
    returnGeometry: true,
    f: "json",
    outSR: 102100
  };

  const result = await arcgisPostJson<QueryResponse>(queryUrl, params);

  if (result.error) {
    throw new Error(`Query at point failed: ${result.error.message}`);
  }

  return result.features || [];
}

function calculateCentroid(rings: number[][][]): { x: number; y: number } {
  const ring = rings[0]; // Use first ring
  let sumX = 0, sumY = 0;

  for (const point of ring) {
    sumX += point[0];
    sumY += point[1];
  }

  return {
    x: sumX / ring.length,
    y: sumY / ring.length
  };
}

// Execute route action - get driving directions between two addresses
async function executeRoute(step: QueryStep): Promise<Feature[]> {
  if (!step.address) {
    throw new Error("Route action requires an origin address");
  }
  if (!step.destinationAddress) {
    throw new Error("Route action requires a destination address");
  }

  // Geocode the origin address
  const originResult = await executeGeocode({ ...step, address: step.address } as QueryStep);
  if (originResult.length === 0) {
    throw new Error(`Could not geocode origin address: ${step.address}`);
  }
  const originGeom = originResult[0].geometry;
  if (!originGeom?.x || !originGeom?.y) {
    throw new Error(`Invalid origin geometry for address: ${step.address}`);
  }

  // Geocode the destination address
  const destResult = await executeGeocode({ ...step, address: step.destinationAddress } as QueryStep);
  if (destResult.length === 0) {
    throw new Error(`Could not geocode destination address: ${step.destinationAddress}`);
  }
  const destGeom = destResult[0].geometry;
  if (!destGeom?.x || !destGeom?.y) {
    throw new Error(`Invalid destination geometry for address: ${step.destinationAddress}`);
  }

  // Get the route
  const routeInfo = await getRoute(
    { x: originGeom.x, y: originGeom.y },
    { x: destGeom.x, y: destGeom.y }
  );

  if (!routeInfo) {
    throw new Error("Could not calculate route");
  }

  // Return a feature with route information
  return [{
    attributes: {
      ORIGIN: step.address,
      DESTINATION: step.destinationAddress,
      DISTANCE_MILES: routeInfo.totalDistance.toFixed(2),
      TIME_MINUTES: Math.round(routeInfo.totalTime),
      _routeInfo: routeInfo,
      _originGeometry: originGeom,
      _destGeometry: destGeom
    },
    geometry: {
      paths: routeInfo.geometry.paths,
      spatialReference: routeInfo.geometry.spatialReference
    }
  }];
}

// Get driving route between two points using ArcGIS Online routing service
export async function getRoute(
  fromPoint: { x: number; y: number },
  toPoint: { x: number; y: number }
): Promise<RouteInfo | null> {
  if (!ARCGIS_API_KEY) {
    console.warn("No ARCGIS_API_KEY configured, skipping routing");
    return null;
  }

  try {
    // The routing service expects stops in format: longitude,latitude (WGS84)
    // Our points are in Web Mercator (102100), need to convert
    const fromWgs84 = webMercatorToWgs84(fromPoint.x, fromPoint.y);
    const toWgs84 = webMercatorToWgs84(toPoint.x, toPoint.y);

    const stops = `${fromWgs84.lon},${fromWgs84.lat};${toWgs84.lon},${toWgs84.lat}`;

    const params = new URLSearchParams({
      f: "json",
      token: ARCGIS_API_KEY,
      stops: stops,
      returnDirections: "true",
      returnRoutes: "true",
      directionsLanguage: "en",
      outSR: "102100"
    });

    const response = await fetch(`${ROUTING_URL}?${params.toString()}`);

    if (!response.ok) {
      console.error(`Routing request failed: ${response.status} ${response.statusText}`);
      return null;
    }

    const data = await response.json();

    if (data.error) {
      console.error("Routing error:", data.error);
      return null;
    }

    if (!data.routes?.features?.length) {
      console.warn("No route found");
      return null;
    }

    const route = data.routes.features[0];
    const directionsData = data.directions?.[0];
    const directionFeatures = directionsData?.features || [];

    // Debug logging
    console.log("Route attributes:", JSON.stringify(route.attributes, null, 2));
    console.log("Directions data keys:", directionsData ? Object.keys(directionsData) : "none");
    console.log("Direction features count:", directionFeatures.length);
    if (directionFeatures.length > 0) {
      console.log("First direction attributes:", JSON.stringify(directionFeatures[0]?.attributes, null, 2));
    }

    // Extract directions - the attribute names vary by service version
    const directions = directionFeatures.map((d: any) => {
      const attrs = d.attributes || {};
      return {
        text: attrs.text || attrs.Text || attrs.directionText || attrs.string || "",
        length: attrs.length || attrs.Length || attrs.driveDistance || 0,
        time: attrs.time || attrs.Time || attrs.ETA || 0
      };
    }).filter((d: any) => d.text); // Filter out empty directions

    return {
      totalDistance: route.attributes.Total_Miles || route.attributes.Total_Length ||
                     (route.attributes.Shape_Length ? route.attributes.Shape_Length * 0.000621371 : 0),
      totalTime: route.attributes.Total_TravelTime || route.attributes.Total_Time ||
                 route.attributes.Total_Minutes || 0,
      directions,
      geometry: {
        paths: route.geometry.paths,
        spatialReference: { wkid: 102100 }
      }
    };
  } catch (error) {
    console.error("Routing error:", error);
    return null;
  }
}

// Convert Web Mercator coordinates to WGS84 (lat/lon)
function webMercatorToWgs84(x: number, y: number): { lat: number; lon: number } {
  const lon = (x / 20037508.34) * 180;
  let lat = (y / 20037508.34) * 180;
  lat = (180 / Math.PI) * (2 * Math.atan(Math.exp(lat * Math.PI / 180)) - Math.PI / 2);
  return { lat, lon };
}
